server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:EmiiFernandez/config-server-dmh.git
          ignoreLocalSshSettings: true
          hostKey: AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
          hostKeyAlgorithm: ssh-rsa
          defaultLabel: main # Rama del repositorio
          privateKey: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKAIBAAKCAgEAqXLzQgQFUAKEmP525cp6WXiJvMPmez18aQ0vjbUs44L3Uwdg
            GuIftoJMocrHe1gqI9pkgNyeJn10yCYVJGq/XZ4RmDWWktxT187suwwipNuMZYU0
            JbfR8EaYstG2t3Xeqd0ZlPNWbTg9VRPgBpVQ81oPggL6AFAadI+J6WcarQ+XYCjs
            Y4RlTYtnX+IDVUXLGJ0W+GnvpwhGz6WTRgg1DoyK7teBsE3FAtlrWuWwouiYTjHi
            rL0I4f0cJIK8GYaqzxBivSBsJ0E0aPI1LT5rMgDtYWlTobnnqJz8u1DKWcvCuhqj
            KcgXLs76g+R4Hv8A0RcV4NQ1hvPm7cniWEba+ysef0oKwNibATeSROuIjnCQr3W6
            T8e4PLveBth6JMc/sfbTsnrt9V7zr+fJz8urNEwoOU18whIEIRi681T0iK4wQ87A
            Zeth/pzd2kmUTyYYa8NtRtqXBs2tJ3nh3p1q2POZTXxUPa86ybia3r07aytbnoCU
            dXGTMWUdBXjE6HPc1++rpBJgr4PTkkLmyDk+02LO7pLUgtj0JLWkMu5qPS4FERq8
            xKhJg0msTSjhaCdEA5iYPlUx9fe7PUHOga9TTF5xdKwKekU7uHq0FoReSNhqSRNR
            LtEUvvPaVru23YNixcORRjMLxbM0FG8LeRn4OgpyBgSODTFr11NsW66Yk8kCAwEA
            AQKCAgBsAuD60LNON/yrxXCms3Vf+MzbrYgKQLw//m60hqtRbtcWbtoc6MzMOqx8
            aVTU0/MwnXJ5Dagl4syBFH1flEfddffDLU2I2bb8FmOiK28d5PDOeaUu8ch5v5Zw
            TeuJcDH51v0KjD4oKrQ1uhCQQbezF1JRTnJrpqPmbuS7CcTgUdLtMcjU+rzUPCst
            3FTBk1aNnvzYZjakI0t36xRAjNS9LGsXKfn6FuihE1QyQb1haqBDH9tcvradzwiU
            YV1jbAsPKGO4KKWoNBEjYFjzORl9a0flUw1DRsxbF46mHC6QJKlAleAxruDQLpFT
            Z1wGbgfoQC3q/XoNRwWJx6lnGetVK7NO+Woja9nsWlRgvJGdBDIrswXbRacRoX6j
            wI47zB1+/lj+tYgdRZ2gWAvyNgpHWkxSxBz4SdrX/7llt1OmXIiWl05Ps0OJrfXY
            6m9IsDXVaMN1EJd+bMe6XkcQujZKxHfw50fRmIe2Hlp3dKYfrrm9E8xpmdQuKvmw
            MFik+zGnvM8eahW4kxqgI88jjAnSNmvsxXKu9FpeTZuWH8E+oXjgQH6U+WFJpLBl
            kFV7NBkuDl3Jr0jMzpHqPg9QAkDf6LDb9+8g6xU33daamt1aJvfHlFEAq0+RXTVP
            EmeSIli9AAEu5vfybW19qR0fOLlfR548u+ojQJyKkxNeKwb1gQKCAQEA0gSdGQkw
            sd54vnUnnXW/KV+PFakEgnNl8xOChi3Pz4CMV9dQ2NaYOqgC9ibagLrcIm3PeXO1
            J6flkti5W6j6iXFSWMFqznJKZfHip2IfEPDnEzsZJv9daIPZ/F+9Ckrg565ix+fx
            T6DNtQ4LBu2sqF4Xys4TyV9pw4GnOCmXGqoLpUH0gh/bBvN4jNogtlMfsN+gUNcc
            zTExUn244jyMAKCPavoSk2k6xjwi48FAqoYERfTwFc9aLqrBVipjeTYGKzEier3n
            9mBra7VgGVF8y7aENrSdWRYRYv8FM2JNCFUYCHHsdJQJpJVzEty90PN6k6Kndpmj
            NrrAf2l5iPUu8QKCAQEAzox32L4senZN3/5NWW7J00WxYe1VLTIds3UmwcexoMzD
            SoEgkXkYb3/3c3CCpiCq/IX+Vtvj6FMwObi+LSFVs/JkySFGBm7AW3jxuwN0VYIU
            ys+fMvxCi89kCqEBG0QRysJ7RtrbBTwyTuKNv01hbvLwKJZfKuWapOkrSokC35bT
            raOuMhg70gFZjopCV5GJw+0LEtAtWU3aAtkw8yx4YlYD8UbWoSuj0/E7oFkE+G9T
            BD+mlU9ahOwHgwmnThaLa1x7S3chwKXbwzTO9UyoVVH65gIr8wIZdT1RGvcEIUvh
            7N52BixTiNUKdwl9QHKnnq6ksHZxxQLa1jSZUZNiWQKCAQA/hwW+PPlt1E3Rzr5c
            8vEQIse1VZr3mtCL5qrky5bAvbG2IHtkHAWQOKIsszQFHIDaKT1JD6cMh8z5znTD
            NSoTySOPlXIpYIkArVpSJ2weQ8CiII5LLZOjub6GiK82HdBKRIW80nw8CfgvfD/5
            qItBorSvtAZoM2Rary1V377FYgqDwp+jfN9UCvG8KX8bp6k+Z2anDWq45th0i3MR
            fB8dUXQQd/SGgp40uJwVKK/W5RMF1kGJV1+AHka9ObU9RQo4pnQ3jJpN/HyB6CtZ
            fTyyolL7+UZfXD2GJH3+PQ3wJ01NwKg121HPZyWX3w3L1tqNLfZZ+b9VHsh7wfvx
            YbkBAoIBAQDKsokumDrYF1+HMW5BFPtVrbBNNPcA+oyxP4fAZbPI5QnGBQCsIpW7
            Xm69yC0+0RJb7TdTkEmSBoluLAHeEjej93228ENjLq7xVbiMWfCBtb2n5qcKBwtb
            XzSDRcvrMRrwy3jlaQPFmHSae7S1hz/V/O14N1G/rEHeEsEcTWcXe1HStq3NlYCn
            MBHuU3qVq0ryjp7uYIQQftkzMGfcTMj7YARQdL9OvZ/x72wfiRzanY1vvvNA1fY0
            OdmJXCDm/jLmMoUA4zGpeFs5r4pmqksMJ/68WGc+/NF0/66ncsCH2IsnxI04s6lq
            v/+cICDd7WbXz/XpAuPVfl66FjZcGvJJAoIBABda8U9wS4WnL2quAl79ZYh42SwZ
            TI3r+bx3AZXMPqDfHKLQwYtS1v3qWzv5+0udbqDnSZAG0UsIpDhaOZXFBfC8fKcn
            COl4PHnQZZK9tfNKo5iWsauUAcFNZyeYmYgS/QXDDd+apUCoJmuw9jb2oaf1KIKV
            uXnbCY5Y3OsejXWhxFI9Y56AZJYz/iIGKmWs6tPyxeyZhwkMH4gjWbYMj2oErsOn
            /ovz4j3806xI05pas6of9PrJnDqwBnRuklYLb4Su20WJxlDfT/P0NBbNbiE0xKFQ
            EKu1/nUzsr6LRSKXaGSZkLV8iKtwmFnRsjqFk+s1EuVgzJTQRDBU3kL/GFc=
            -----END RSA PRIVATE KEY-----

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: http://localhost:${server.port}/actuator/info
    healthCheckUrlPath: http://localhost:${server.port}/actuator/health
